"use client";

import './globals.css'
import Navbar from '@/src/navbar'
import Providers from '../redux/Providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body>
          <Providers>
              <Navbar />
              {children}
          </Providers>
        </body>
      </html>
  )
}
